### ISSUE TITLE
Content: listing Speakers and Sessions

### ISSUE THREAD

**Issue by ianschuler** [satsummit/satsummit.github.io#106]
@ricardoduplos @danielfdsilva how close is the website to accommodating speakers and/or session pages? Great if we can post a full agenda, but at the very least we'd like to start advertising speakers and content.

**Comment by ricardoduplos** [comment]
@ianschuler the website is ready to accommodate both speakers and sessions content.

You can check it here: https://github.com/satsummit/satsummit.github.io/tree/feature/speakers

**Comment by danielfdsilva** [comment]
@ianschuler for now the work is still in a branch. Let's add a couple of entries so it is not empty and then we'll merge. Let us know if you need help
