### ISSUE TITLE
Add Sponsor logos

### ISSUE THREAD

**Issue by kcarini** [satsummit/satsummit.github.io#263]
We have a first batch of sponsors close to ready to announce and need to get logos added to the website.

- [ ] Media Partner: [GeoAwesome](https://drive.google.com/file/d/1_QjqsbReFPNdIKjNMv76ihcP1jAkQRrC/view?usp=drive_link)
- [ ] Institutional Partner: PT Space (need logo file)
- [ ] Level? [AWS](https://drive.google.com/file/d/1Xq-R6FNnVxg29oYB9DM0vULg6thOYuNj/view?usp=drive_link)
- [ ] Bronze: Degas Limited (need logo)

@olafveerman when we get Degas and PT Space logos can you please add the links? And confirm the AWS level once that agreement is signed?

**Comment by olafveerman** [comment]
PT Space logos:

* [English](https://github.com/user-attachments/files/17057485/ENGL.zip)
* [Portuguese](https://github.com/user-attachments/files/17057486/PT.zip)
